db/seeds.rb
juste de la seed en commentée. Je commence juste
=> V1 à peine touchée

app/controllers/categories_controller.rb, app/controllers/quests_controller.rb, app/controllers/skins_controller.rb, app/controllers/user_goals_controller.rb, app/controllers/user_quests_controller.rb, app/controllers/user_skins_controller.rb, app/controllers/users_controller.rb, app/models/goal.rb, app/models/goal_skill.rb, app/models/quest.rb, app/models/skill.rb, app/views/categories/index.html.erb, app/views/categories/show.html.erb, app/views/quests/show.html.erb, app/views/skins/edit.html.erb, app/views/skins/index.html.erb, app/views/skins/show.html.erb, app/views/user_goals/new.html.erb, app/views/user_quests/show.html.erb, app/views/users/edit.html.erb, app/views/users/show.html.erb, config/routes.rb, test/controllers/categories_controller_test.rb, test/controllers/quests_controller_test.rb, test/controllers/skins_controller_test.rb, test/controllers/user_goals_controller_test.rb, test/controllers/user_quests_controller_test.rb, test/controllers/user_skins_controller_test.rb, test/controllers/users_controller_test.rb
added all controllers and routes
=> Controllers

app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_navbar_card.scss, app/assets/stylesheets/components/_progress_bar.scss, app/views/pages/home.html.erb
Prêt pour le déplacement du front sur user show
=> Seconde partie front de la homepage et components (alex)

app/models/goal.rb, app/models/goal_skill.rb, app/models/quest.rb, app/models/skill.rb, config/routes.rb, db/migrate/schema.rb, db/seeds.rb
Remise à niveau et corrections des controllers, des routes et des models
=> routes, controllers and models updated

app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_cellules.scss, app/assets/stylesheets/components/_index.scss
Ajout d'un type de cellule dans les components
=> ajout component cellules

app/controllers/application_controller.rb, app/controllers/categories_controller.rb, app/models/quest.rb, app/views/categories/index.html.erb, app/views/categories/show.html.erb, app/views/devise/registrations/new.html.erb, app/views/pages/home.html.erb, db/migrate/20221130111925_add_name_to_user.rb, db/schema.rb, db/seeds.rb
je balance les 2 pages pour qu'Alex deal avec+ DB fixed et user registration fixed
=> quests V1 = category-index + category-show fait

app/views/skins/index.html.erb, app/views/skins/show.html.erb, app/views/users/show.html.erb, db/seeds.rb
Minor fixes and Cloudinary is now working with jpeg instead of png
=> User journey by adri

app/assets/stylesheets/components/_buttons.scss, app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_cellules.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_progress_bar.scss, app/assets/stylesheets/components/_skins.scss, app/assets/stylesheets/pages/_home.scss, app/views/categories/index.html.erb, app/views/quests/show.html.erb, app/views/users/show.html.erb
=> front de quest show en cours, components et container en cours

app/controllers/user_quests_controller.rb, app/views/quests/show.html.erb
on arrive jusqu'à userquest create. Je dois faire des boutons stop et retour convennable.
=> arrivé à user_goals#new

app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_cellules.scss, app/assets/stylesheets/components/_dropdown.scss, app/assets/stylesheets/components/_fonts_and_titles.scss, app/assets/stylesheets/components/_more_bar.scss, app/views/user_goals/new.html.erb, app/views/users/show.html.erb
footer de la root page à continuer et timer sur le user_goal new à initier
=> front user_goal new et details autres

app/controllers/skins_controller.rb, app/controllers/user_skins_controller.rb, app/views/categories/show.html.erb, app/views/skins/index.html.erb, app/views/skins/show.html.erb
Seed updated, User Journey on skins reached UserSkin#create + minor fixes
=> reached Create on User_Skin

app/controllers/user_skins_controller.rb, app/models/user.rb, app/models/user_skin.rb, app/views/categories/index.html.erb, app/views/categories/show.html.erb, app/views/quests/show.html.erb, app/views/skins/index.html.erb, app/views/skins/show.html.erb, app/views/user_goals/new.html.erb, app/views/users/show.html.erb
User journey for skins done. Can now update the profil page photo from skins gallery
=> user journey on skins done

app/assets/stylesheets/components/_buttons.scss, app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_dropdown.scss, app/assets/stylesheets/components/_fonts_and_titles.scss, app/assets/stylesheets/pages/_home.scss, app/views/categories/show.html.erb, app/views/quests/show.html.erb, app/views/user_quests/show.html.erb, public/404.html, public/500.html
=> Dropdown fixes, user_goal#new front done and 404 and 500 done

app/controllers/user_goals_controller.rb, app/controllers/user_quests_controller.rb, app/javascript/controllers/index.js, app/javascript/controllers/quest_counter_controller.js, app/views/user_goals/new.html.erb, app/views/user_quests/show.html.erb, package.json, yarn.lock
lien du bouton de la boucle "finish" établit + 1er threshold atteint. 
prochaine etape: passer au 2 treshold
=> 1er threshold atteint; on doit passer au 2eme

app/javascript/controllers/quest_counter_controller.js, app/views/user_goals/new.html.erb
attention car mon code en JS risque de bouger avec le changement vis à vis de la db.
=> debut  de user goal create mais surement à revoir

app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_cellules.scss, app/assets/stylesheets/components/_navbar_card.scss, app/javascript/controllers/chartpage_controller.js, app/views/skills/index.html.erb
Graph terminé, petit souci esthétique à voir (color)
=> Stats index graph doneeee

app/assets/stylesheets/components/_dropdown.scss, app/javascript/controllers/dropdown_controller.js, app/javascript/controllers/index.js, app/views/quests/show.html.erb
le dropdown est terminé, reste à le dupliquer par le nombre d'étapes
=> dropdown dans les points d'étapes de load bar

app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_dropdown.scss, app/assets/stylesheets/components/_fonts_and_titles.scss, app/assets/stylesheets/components/_more_bar.scss, app/assets/stylesheets/components/_skins.scss, app/javascript/controllers/chartpage_controller.js, app/views/shared/_yellow_navbar.html.erb, app/views/user_goals/new.html.erb, app/views/user_quests/show.html.erb, app/views/users/show.html.erb, db/schema.rb, db/seeds.rb, yarn.lock
Chat avatar terminé en tant que skin default et full fonctionnel sur toutes les pages (testé)
=> Chat avatar

app/assets/stylesheets/components/_skins.scss, app/views/quests/show.html.erb, app/views/skills/index.html.erb, app/views/user_goals/new.html.erb, app/views/users/show.html.erb
Changement dans les dropdown, profil chat en default et avatar enlevé, correction bug treshold
=> dropdown dot en cours , manque les differences

app/assets/stylesheets/components/_animated_font.scss, app/assets/stylesheets/components/_dropdown.scss, app/assets/stylesheets/components/_fonts_and_titles.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_more_bar.scss, app/assets/stylesheets/components/_progress_bar.scss, app/assets/stylesheets/config/_fonts.scss, app/javascript/controllers/chart_js_controller.js, app/views/categories/index.html.erb, app/views/categories/show.html.erb, app/views/skills/index.html.erb, app/views/user_goals/new.html.erb, app/views/user_quests/show.html.erb, app/views/users/show.html.erb, db/schema.rb
=> font des categories termine et corrigé pour iphone 11

app/assets/stylesheets/components/_fonts_and_titles.scss, app/assets/stylesheets/components/_more_bar.scss, app/assets/stylesheets/components/_progress_bar.scss, app/assets/stylesheets/components/_progress_bar_2.scss, app/assets/stylesheets/components/_skins.scss, app/assets/stylesheets/pages/_home.scss, app/views/user_goals/new.html.erb
The app is now correct on desktop view
=> Responsive

app/assets/stylesheets/components/_buttons.scss, app/assets/stylesheets/components/_dropdown.scss, app/assets/stylesheets/components/navigation.scss, app/javascript/controllers/tutorial_controller.js, app/views/users/show.html.erb
CTA position test, Refacto and js for tutorial
=> little changes on design
